version: '2.3'

services:
  embedder:
    restart: always
    container_name: embedder
    mem_limit: 4G

    build:
      context: ./embedder
      dockerfile: Dockerfile
    image: embedder:latest
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port ${EMBEDDER_PORT}"

    environment:
      - NVIDIA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES_EMB}
      - SPECIFIC_MODEL=${SPECIFIC_MODEL}
      - TRANSFORMERS_CACHE=${TRANSFORMERS_CACHE}

    volumes:
      - ./embedder:/embedder

      # TEST ONLY
      - /home/orange_lime/.cache/huggingface/hub:/cache/

    ports:
      - ${EMBEDDER_PORT}:${EMBEDDER_PORT}

  mysql:
    restart: always
    container_name: mysql
    mem_limit: 500m
    image: mysql:5.6  # Choose your desired MySQL version

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Required for MySQL
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./eee/my.cnf:/etc/mysql/my.cnf
    ports:
      - ${DB_PORT}:${DB_PORT}
